Repository IT-Cotato/11th-StageMate-FE, pull requests merged in 2025-07, with the labels that each got.

#2 feat/#1: 메인 페이지 헤더 UI
  public/img/mock-poster1.png
  public/img/mock-poster2.png
  public/img/mock-poster3.png
  src/App.tsx
  src/assets/alerts-feedback/bell.svg
  src/assets/chevrons/chevron-down.svg
  src/assets/logos/main-logo.svg
  src/assets/react.svg
  src/assets/search.svg
  src/assets/users/user.svg
  src/components/main/Header.tsx
  src/components/main/LoggedInHeader.tsx
  src/components/main/LoggedOutHeader.tsx
  src/components/main/MainButton.tsx
  src/components/main/SearchBox.tsx
  src/components/main/WeekCalendar.tsx
  src/index.css
  src/pages/MainPage.tsx
Labels: enhancement

#4 feat/#3: 메인 페이지 캘린더 UI
  package-lock.json
  package.json
  src/assets/hearts/empty-heart.svg
  src/assets/hearts/full-heart.svg
  src/components/main/CalendarButton.tsx
  src/components/main/ScheduleItem.tsx
  src/components/main/ScheduleList.tsx
  src/components/main/WeekCalendar.tsx
  src/pages/MainPage.tsx
  src/types/schedule.ts
Labels: enhancement

#11 feat/#7: 로그인 페이지 UI 구현
  src/assets/bottomNavigationBar/home-outline.svg
  src/assets/brands/apple-light.svg
  src/assets/brands/facebook-light.svg
  src/assets/brands/google-light.svg
  src/assets/brands/twitter-light.svg
  src/assets/checkbox/checkbox-blank.svg
  src/assets/checkbox/checkbox-fill.svg
  src/assets/chevrons/chevron-left.svg
  src/components/auth/BrandBadges.tsx
  src/components/global/ButtonFill.tsx
  src/components/global/ButtonStroke.tsx
  src/components/global/PageHeader.tsx
  src/components/main/CalendarButton.tsx
  src/components/main/Magazine.tsx
  src/components/main/PlayTag.tsx
  src/components/main/RecommendedPlayItem.tsx
  src/components/main/ScheduleItem.tsx
  src/components/ui/checkbox/CustomCheckbox.tsx
  src/index.css
  src/pages/auth/LoginPage.tsx
Labels: enhancement

#14 refactor/#13: Schedule 컴포넌트 구조 리팩토링 및 의존성 분리
  src/components/main/ScheduleItem.tsx
  src/components/main/ScheduleList.tsx
  src/mocks/mockSchedules.ts
  src/pages/MainPage.tsx
Labels: enhancement

#18 chore/#15: 디자인 수정 사항 반영
  src/assets/main-header-bg/header-bg.svg
  src/components/NavigationBar.tsx
  src/components/main/CalendarButton.tsx
  src/components/main/Header.tsx
  src/components/main/LoggedInHeader.tsx
  src/components/main/LoggedOutHeader.tsx
  src/components/main/Magazine.tsx
  src/components/main/MainButton.tsx
  src/components/main/PlayTag.tsx
  src/components/main/RecommendedPlayItem.tsx
  src/components/main/RecommendedPlayList.tsx
  src/components/main/ScheduleItem.tsx
  src/components/main/ScheduleList.tsx
  src/components/main/SearchBox.tsx
  src/components/main/WeekCalendar.tsx
  src/index.css
  src/layout/MainLayout.tsx
  src/pages/MainPage.tsx
Labels: enhancement

#23 Feat/#19 회원가입 폼 페이지 구현
  src/App.tsx
  src/assets/vector-check/vector-check-confirmed.svg
  src/assets/vector-check/vector-check-default.svg
  src/components/auth/StateButtonStroke.tsx
  src/pages/auth/SignupFormPage.tsx
  src/util/validation.ts
Labels: enhancement

#24 style/#16: PageHeader 컴포넌트의 디자인 수정
  src/components/global/PageHeader.tsx
Labels: enhancement

#32 feat/#20: 커뮤니티 메인 페이지 UI
  src/App.tsx
  src/assets/community/bookmark.svg
  src/assets/community/community-chat.svg
  src/assets/community/daily-post-musical-note.svg
  src/assets/community/hot-post-rocket.svg
  src/assets/community/live-chat-door.svg
  src/assets/community/live-chat-users.svg
  src/assets/community/live-chat-wifi.svg
  src/assets/community/share-post-diamond.svg
  src/assets/community/tip-post-school.svg
  src/assets/logos/community-logo.svg
  src/components/community/chat/ChatRoomItem.tsx
  src/components/community/chat/ChatRoomList.tsx
  src/components/community/common/CommunityCategory.tsx
  src/components/community/common/CommunityMainHeader.tsx
  src/components/community/common/LoadMoreButton.tsx
  src/components/community/magazine/PlayMagazine.tsx
  src/components/community/post/PostCardItem.tsx
  src/components/community/post/PostItem.tsx
  src/components/community/post/PostList.tsx
  src/components/community/post/SharePostList.tsx
  src/components/global/CategoryBadge.tsx
  src/layout/CommunityMainLayout.tsx
  src/mocks/mockChatRooms.ts
  src/mocks/mockMagazine.ts
  src/mocks/mockPosts.ts
  src/mocks/mockSharePosts.ts
  src/pages/CommunityPage.tsx
  src/pages/community/CommunityMainPage.tsx
  src/types/community.ts
Labels: enhancement

#34 fix/#31: 온보딩 관련 스타일 설정 수정
  src/components/modal/OnboardingModal/OnboardingModal.tsx
  src/components/modal/OnboardingModal/OnboardingWrapper.tsx
Labels: enhancement

#35 feat/#33: 게시글 에디터 UI
  package-lock.json
  package.json
  src/App.tsx
  src/assets/community/community-content-nav-chat.svg
  src/assets/community/community-content-nav-heart.svg
  src/assets/community/editor-icons/editor-icon-background-color.svg
  src/assets/community/editor-icons/editor-icon-bell.svg
  src/assets/community/editor-icons/editor-icon-bold.svg
  src/assets/community/editor-icons/editor-icon-check.svg
  src/assets/community/editor-icons/editor-icon-color.svg
  src/assets/community/editor-icons/editor-icon-cross-linear.svg
  src/assets/community/editor-icons/editor-icon-image.svg
  src/assets/community/editor-icons/editor-icon-italic.svg
  src/assets/community/editor-icons/editor-icon-link.svg
  src/assets/community/editor-icons/editor-icon-lock.svg
  src/assets/community/editor-icons/editor-icon-plus-minus.svg
  src/assets/community/editor-icons/editor-icon-text-center.svg
  src/assets/community/editor-icons/editor-icon-text-left.svg
  src/assets/community/editor-icons/editor-icon-text-right.svg
  src/assets/community/editor-icons/editor-icon-underline.svg
  src/assets/community/share.svg
  src/components/community/common/CommunityCategory.tsx
  src/components/community/content/ContentEditor.tsx
  src/components/community/content/ContentFooterBar.tsx
  src/components/community/content/ContentHeader.tsx
  src/components/community/content/EditorMenuBar.tsx
  src/components/community/content/EditorToggleButton.tsx
  src/components/community/content/EditorToggleSection.tsx
  src/components/community/content/ShareBadgeSection.tsx
  src/components/community/content/lib/CustomLink.ts
  src/components/community/content/lib/FontSize.ts
  src/components/global/CategoryBadge.tsx
  src/constant.ts
  src/index.css
  src/layout/CommunityContentLayout.tsx
  src/pages/community/CommunityEditPage.tsx
Labels: enhancement

#41 style/#39: 하단 네비게이션 바 크기 조절
  src/components/global/MainNavigationBar.tsx
  src/layout/MainLayout.tsx
Labels: documentation

#47 style/#36: secondary 색상 코드 수정
  src/components/community/post/PostItem.tsx
  src/components/global/CategoryBadge.tsx
  src/components/main/WeekCalendar.tsx
  src/index.css
  src/pages/auth/SignupFormPage.tsx
Labels: documentation

#50 feat/#45: 나의 아카이빙 메인 페이지 UI
  package-lock.json
  package.json
  src/App.tsx
  src/assets/archive/archive-plus.svg
  src/assets/archive/archive-star.svg
  src/assets/chevrons/chevron-up.svg
  src/components/archive/ArchiveCalendar.css
  src/components/archive/ArchiveCalendar.tsx
  src/components/archive/ScrappedMagazineList.tsx
  src/components/archive/TopRatedShowList.tsx
  src/components/community/post/PostCardItem.tsx
  src/components/community/post/PostListItem.tsx
  src/layout/ArchiveLayout.tsx
  src/mocks/mockMagazine.ts
  src/mocks/mockPosts.ts
  src/mocks/mockTopRatedShows.ts
  src/pages/ArchivePage.tsx
  src/types/community.ts
Labels: enhancement

#51 feat/#42: 매거진 리스트 및 매거진 디테일 페이지 UI 구현
  src/App.tsx
  src/assets/hearts/empty-heart.svg
  src/components/community/chat/ChatRoomList.tsx
  src/components/community/common/LoadMoreButton.tsx
  src/components/community/magazine/MainMagazine.tsx
  src/components/community/magazine/PlayMagazine.tsx
  src/components/community/magazine/SubMagazine.tsx
  src/components/community/post/PostItem.tsx
  src/components/community/post/PostListItem.tsx
  src/components/main/PlayTag.tsx
  src/components/main/RecommendedPlay.tsx
  src/components/main/ScheduleItem.tsx
  src/constant.ts
  src/mocks/mockMagazineDetail.ts
  src/mocks/mockMagazinePosts.ts
  src/mocks/mockSubMagazinePosts.ts
  src/pages/community/MagazineDetailPage.tsx
  src/pages/community/MagazinePage.tsx
  src/types/community.ts
Labels: enhancement

#61 refactor/#55: 게시글 에디터 메뉴 툴바 카메라, 색상 기능 제거
  src/assets/community/editor-icons/editor-icon-background-color.svg
  src/assets/community/editor-icons/editor-icon-color.svg
  src/components/community/content/EditorMenuBar.tsx
  src/hooks/useClickOutside.ts
Labels: documentation, enhancement

#68 feat/#49: 게시글 상세 ui
  src/App.tsx
  src/assets/community/modal-icons/arrow-reply.svg
  src/assets/community/modal-icons/ban.svg
  src/assets/community/modal-icons/exclamation.svg
  src/assets/community/modal-icons/pencil.svg
  src/assets/community/modal-icons/trash.svg
  src/components/community/chat/ChatRoomItem.tsx
  src/components/community/chat/ChatRoomList.tsx
  src/components/community/magazine/PlayMagazine.tsx
  src/components/community/post/CommentItem.tsx
  src/components/community/post/FilteredPostList.tsx
  src/components/community/post/PostCardItem.tsx
  src/components/community/post/PostItem.tsx
  src/components/community/post/PostList.tsx
  src/components/community/post/PostListItem.tsx
  src/components/community/post/SharePostList.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/PostOptionModal.tsx
  src/hooks/useCommunityListNavigation.ts
  src/hooks/useCommunityNavigation.ts
  src/hooks/useScrollLockwithRestore.ts
  src/index.css
  src/layout/CommunityContentLayout.tsx
  src/pages/community/CommunityMainPage.tsx
  src/pages/community/CommunityPostPage.tsx
  src/types/categoryMap.ts
Labels: enhancement

#77 style/#76: 디자인 수정 사항 반영 및 스타일 개선
  src/components/archive/ArchiveCalendar.tsx
  src/components/archive/ScrappedMagazine.tsx
  src/components/community/common/LoadMoreButton.tsx
  src/components/community/post/PostItem.tsx
  src/components/main/LoggedInHeader.tsx
  src/components/main/LoggedOutHeader.tsx
  src/components/main/MainButton.tsx
  src/components/main/MainHeader.tsx
  src/components/search/SearchBox.tsx
Labels: documentation
