Repository IT-Cotato/11th-StageMate-FE, pull requests merged in 2025-08, with the labels that each got.

#87 feat/#85: 커뮤니티 카테고리별 에디터 로직 연결
  src/components/community/common/CommunityCategory.tsx
  src/components/community/content/ContentEditor.tsx
  src/components/community/content/EditorMenuBar.tsx
  src/components/community/post/FilteredPostList.tsx
  src/pages/community/CommunityEditPage.tsx
  src/types/categoryMap.ts
  src/util/categoryMapper.ts
Labels: enhancement

#95 style/#94: 커뮤니티 메인 페이지 디자인 수정 사항 반영
  src/assets/community/magazine-picture.svg
  src/components/archive/ScrappedMagazine.tsx
  src/components/archive/ScrappedMagazineList.tsx
  src/components/community/chat/ChatRoomItem.tsx
  src/components/community/chat/ChatRoomList.tsx
  src/components/community/common/LoadMoreButton.tsx
  src/components/community/magazine/PlayMagazine.tsx
  src/components/community/post/PostCardItem.tsx
  src/components/community/post/PostHeaderInfo.tsx
  src/components/community/post/PostItem.tsx
  src/components/community/post/PostList.tsx
  src/components/community/post/PostListItem.tsx
  src/components/community/post/SharePostList.tsx
  src/components/global/LoadMoreButton.tsx
  src/components/main/RecommendedPlay.tsx
  src/pages/community/CommunityMainPage.tsx
Labels: documentation

#93 feat/#88: 셋팅-이용 안내 페이지 하위 페이지 UI 구현
  src/App.tsx
  src/components/global/BackButtonTitleHeader.tsx
  src/components/setting/Announcement.tsx
  src/constants/enquiry.ts
  src/mocks/mockAnnouncementDetail.ts
  src/mocks/mockAnnouncementList.ts
  src/mocks/mockPolicyTerms.ts
  src/mocks/mockPrivacyTerms.ts
  src/pages/setting/AnnouncementDetailPage.tsx
  src/pages/setting/AnnouncementPage.tsx
  src/pages/setting/EnquirePage.tsx
  src/pages/setting/PolicyPrivacyPage.tsx
  src/pages/setting/PolicyTermsPage.tsx
  src/pages/setting/SettingSupportPage.tsx
  src/types/Announcement.ts
  src/types/Policy.ts
Labels: enhancement

#96 feat/#81: 공연 제보 ui
  src/App.tsx
  src/components/community/common/CommunityMainHeader.tsx
  src/components/global/PageHeader.tsx
  src/components/global/TagBadge.tsx
  src/components/main/PerformanceCard.tsx
  src/components/main/PerformanceCardList.tsx
  src/components/main/ScheduleItem.tsx
  src/components/main/ScheduleList.tsx
  src/components/modal/SelectDateModal.tsx
  src/components/modal/SelectGenreModal.tsx
  src/layout/ArchiveLayout.tsx
  src/layout/CalendarLayout.tsx
  src/layout/CommunityMainLayout.tsx
  src/mocks/mockPlaces.ts
  src/pages/SearchPage.tsx
  src/pages/calendar/CalendarPage.tsx
  src/pages/calendar/CalendarReportLocation.tsx
  src/pages/calendar/CalendarReportPage.tsx
  src/pages/calendar/CalendarReportPerformancePage.tsx
  src/pages/main/PerformanceAllPage.tsx
  src/stores/useReportFormStore.ts
Labels: enhancement

#100 feat/#89: 알림함 UI
  src/App.tsx
  src/assets/notification/comment.svg
  src/components/community/common/CommunityMainHeader.tsx
  src/components/global/NotificationCard.tsx
  src/components/main/MainHeader.tsx
  src/mocks/mockNotification.ts
  src/pages/NotificationPage.tsx
  src/util/formatKoreanTime.ts
Labels: enhancement

#108 feat/#99 메인 페이지(홈) 온보딩 모달 1회 표시
  src/components/modal/OnboardingModal/OnboardingWrapper.tsx
  src/pages/main/MainPage.tsx
Labels: bug

#116 feat/#114: 세팅(마이페이지) 문의하기 api 연동
  src/api/mypageApi.ts
  src/api/urls.ts
  src/constants/enquiry.ts
  src/pages/setting/EnquirePage.tsx
  src/types/enquiry.ts
Labels: enhancement

#117 feat/#115: 로그인/로그아웃 진행중 화면 구현
  src/pages/auth/LoginPage.tsx
  src/pages/setting/SettingSupportPage.tsx
Labels: enhancement

#153 feat/#151: 매거진 API 연결
  src/App.tsx
  src/api/magazineApi.ts
  src/api/urls.ts
  src/assets/community/magazine-picture.svg
  src/components/archive/ScrappedPostList.tsx
  src/components/auth/ProtectedRoute.tsx
  src/components/community/magazine/MainMagazine.tsx
  src/components/community/magazine/PlayMagazine.tsx
  src/components/community/magazine/SubMagazine.tsx
  src/components/community/post/FilteredPostList.tsx
  src/components/community/post/PostCardItem.tsx
  src/components/community/post/PostListItem.tsx
  src/components/community/post/SharePostList.tsx
  src/components/ui/LoadingSpinner.tsx
  src/hooks/useMagazine.ts
  src/layout/CommunityMainLayout.tsx
  src/mocks/mockMagazine.ts
  src/mocks/mockMagazineDetail.ts
  src/mocks/mockMagazinePosts.ts
  src/pages/community/CommunityMainPage.tsx
  src/pages/community/MagazineDetailPage.tsx
  src/pages/community/MagazinePage.tsx
  src/pages/community/SharePostsPage.tsx
  src/types/community.ts
Labels: enhancement

#157 docs/#156: VITE_WS_BASE_URL 환경 변수 추가
  .github/workflows/main.yml
Labels: documentation

#163 feat/#162: 마이페이지 - 내가 작성한 글, 내가 댓글 단 글 API 연결
  src/api/mypageApi.ts
  src/api/urls.ts
  src/hooks/useUserContents.ts
  src/pages/ScrappedMagazinePage.tsx
  src/pages/ScrappedPostPage.tsx
  src/pages/WrittenCommentPage.tsx
  src/pages/WrittenPostPage.tsx
  src/pages/archive/ArchivePage.tsx
  src/pages/setting/SettingActivityPage.tsx
  src/types/community.ts
Labels: enhancement

#171 feat/#164 커뮤니티 종합적으로 수정
  src/components/community/content/ContentHeader.tsx
  src/components/community/post/CommentItem.tsx
  src/components/community/post/PostItem.tsx
  src/components/community/post/PostList.tsx
  src/components/community/post/PostListItem.tsx
  src/components/community/post/SharePostList.tsx
  src/components/main/ScheduleItem.tsx
  src/components/modal/PostOptionModal.tsx
  src/layout/CommunityContentLayout.tsx
  src/pages/calendar/CalendarPage.tsx
  src/pages/community/CommunityPostPage.tsx
  src/pages/community/SharePostsPage.tsx
  src/pages/main/MainPage.tsx
  src/stores/useScrapStore.ts
  src/types/communityDetail.ts
  src/types/schedule.ts
  src/util/scheduleMapper.ts
Labels: bug, enhancement

#170 refactor/#169: 오류와 기능을 수정합니다.
  src/App.tsx
  src/components/main/MainHeader.tsx
  src/components/search/SearchBox.tsx
  src/index.css
  src/pages/auth/SignupCompletePage.tsx
  src/pages/auth/SignupFormPage.tsx
  src/pages/community/SharePostsPage.tsx
Labels: bug, enhancement

#177 fix/#176: ui 스타일 수정
  src/components/community/post/CommentInput.tsx
  src/components/community/post/PostItem.tsx
  src/components/community/post/PostList.tsx
  src/components/modal/SelectDateModal.tsx
  src/pages/calendar/CalendarPage.tsx
Labels: bug, enhancement

#182 fix/#181: STOMP 연결 시 액세스 토큰 처리 개선 및 디버깅 로그 추가
  src/api/stompClient.ts
  src/pages/community/ChatRoomPage.tsx
Labels: bug
